### PR TITLE
build docs on both push and pr on ubuntu-latest

### PR DESCRIPTION
**Pull request by Karthik-d-k**
- trying to solve issue #136 .
- run action on ubuntu-latest, hoping this fixes.
- enable mdbook build on pull_requests too.
- draft pr for now.

### CODE REVIEW

**Comment by Karthik-d-k** [comment]
Hi, 
I enables gh-actions on pr (to see if it works before merge), but seems some settings should be changes to enable this
error -->
```
remote: Permission to opeolluwa/racoon.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/opeolluwa/racoon/': The requested URL returned error: 403
```

**Comment by opeolluwa** [comment]
Thank you so much for the effort. I'll look into it again

**Comment by opeolluwa** [comment]
What fascinates me is that it's just the index.html file that is not I included

**Comment by Karthik-d-k** [comment]
yes, 
if we add `-v` flag to `mv` command, we will get to know which files are copied to check whether `index.html` is being copied over or not.
But before that we need to output the list of files generated from `mdbook build` , maybe easy way would be to just execute 
`ls -l book` after `mdbook build`.
this way we will know what miht be the issue i guess !

**Comment by opeolluwa** [comment]
Oh great! 
Could you please do that and make a PR?

**Pull request merged**
